### ISSUE TITLE
Events start/end times may vary

### ISSUE THREAD

**Issue by lifeisfoo** [latina-in-tech/latina-in-tech.github.io#209]
### Description

Date and time object are manipulated directly (e.g. https://github.com/latina-in-tech/latina-in-tech.github.io/blob/main/src/components/event/AddToCalendar.tsx#L32) and this can cause an improper behaviour in mixed environment (SSR and CSR).

The time shown is right only if the date manipulation happens on the client side (see steps below to reproduce).

### Steps to reproduce

- Go to https://www.latinaintech.org/it
- Start/end times are ok
- Click on an event
- See the start/end times (e.g. 7-9pm) - they are ok 
- Reload the page
- Now start/end time are -2h (e.g. 5-7pm) - they are wrong

**Comment by lifeisfoo** [comment]
![IMG_20240501_212810.jpg](https://github.com/latina-in-tech/latina-in-tech.github.io/assets/3725610/e29b65f4-93b4-441d-9b4b-f5456773fd9e)

**Comment by salvatorericcardi** [comment]
@lifeisfoo I guess it happens for add to calendar component on the next events, can you confirm? Because I can't find the bug actually, maybe fixed with the last pr. Try again and let me know, please.

**Comment by Undermaken** [comment]
@salvatorericcardi I just checked and it seems to be fixed!
This issue can be closed from my end
