### ISSUE TITLE
Event list is flickering 

### ISSUE THREAD

**Issue by coluzziandrea** [latina-in-tech/latina-in-tech.github.io#35]
### Description

Right after page opening you can see a bit of flickering happing for the event list, which looks to be loaded after the rest of the page, see video:

![ezgif-2-c5cad1ee2b](https://github.com/latina-in-tech/latina-in-tech.github.io/assets/12852000/b5326eef-98f7-4333-bec7-cd461f728aa9)

Maybe we would need a loading phase, in which we will show a loader to the user

### Steps to reproduce

- open the List website
- wait for a short period
- you should have experienced a bit of flickering

**Comment by Undermaken** [comment]
@coluzziandrea are you still experiencing this flickering?

I believe it should be fixed by

**Comment by coluzziandrea** [comment]
@Undermaken you're right! This can be closed 👍
